### PR TITLE
partial solution for file vs redirectstream problem

### PR DESCRIPTION
**Pull request by rvanheest**
here is some experimenting with the problem that was posed in https://github.com/DANS-KNAW/easy-stage-dataset/pull/109#discussion_r110826703. This PR is not meant for merging, just to give you ideas of how to solve this.

### CODE REVIEW

**Comment by jo-pol** [comment]
You mean this [comment](https://github.com/DANS-KNAW/easy-stage-dataset/pull/109#discussion_r111401396)?

**Comment by rvanheest** [comment]
@janvanmansum I see you merged the 'parent' PR. Do you want to keep this amend around, or can I close/delete it?

**Comment by janvanmansum** [comment]
@rvanheest : Please, close it. I figure @jo-pol has solved the same problem.

**Comment by rvanheest** [comment]
I thought that was a different problem @jo-pol solved. This PR was about deciding between creating the JSON for a file or a redirectstream if I remember correctly. I'll see what is left from it and how it changes given the other PR by @jo-pol. In case it's still valid, I'll do a new PR.

Closing for now...

**Pull request closed without merging**
